##################
# Common Variables
##################

deploymentNamespace: argo-cd
server: https://kubernetes.default.svc


##################
# Version Manifest
##################

applicationVersions:
  frontend: &frontendVersion bad879345e4555507d17c4497273263f466f1eed
  backend: &backendVersion 5e8f772288f95b6044ba9877a6d5f56d2c54b012
  infinispan: &infinispanVersion 1.1.1.Final
  git-api: &gitApiVersion ef3fa1e1fe9dbb6091a0561c776c896b57ba0de1
  launcher: &launcherVersion 3478f8caecf4198b73bdd3beb0efec42f322761a


##################################
# Application Template Definitions
##################################

applications:
- name: omp-frontend
  url: https://github.com/rht-labs/open-management-portal-frontend.git
  path: deployment
  ref: *frontendVersion
  helmValues:
    imageTag: *frontendVersion

- name: omp-backend
  url: https://github.com/rht-labs/open-management-portal-backend.git
  path: deployment
  ref: *backendVersion
  helmValues:
    imageTag: *backendVersion

- name: infinispan-operator
  url: https://github.com/infinispan/infinispan-operator.git
  path: deploy
  ref: *infinispanVersion

- name: git-api
  url: https://github.com/rht-labs/open-management-portal-git-api.git
  path: deployment
  ref: *gitApiVersion
  helmValues:
    imageTag: *gitApiVersion

- name: omp-launcher
  url: https://github.com/redhat-cop/tool-integrations.git
  path: "argo-cd-bridges/gitlab/deploy"
  ref: *launcherVersion
  diffIgnore:
  - group: build.openshift.io
    kind: BuildConfig
    jsonPointers:
    - /status

